# Check Code for Keywords / Credentials

name: code-scan
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Scan for binaries
        run: |
          win_count=$( ls -l -R | grep -E "*.exe" | wc -l )
          echo "Windows Binary count : $win_count"
          sh_count=$( ls -l -R | grep -E "*.sh" | wc -l )
          echo "Shell Script file count : $sh_count"
